### ISSUE TITLE
[FEATURE] - Allow different yaml Loader

### ISSUE THREAD

**Issue by maruiz93** [mkaranasou/pyaml_env#17]
**Is your feature request related to a problem? Please describe.**
Current version uses SafeLoader of PyYaml, but this loader does not allow python object serialization or other custom requirements.

**Describe the solution you'd like**
That parse_config method receive a loader. By default it could be SafeLoader but in that way other people could add more features over that Loader

**Additional context**
The call could be replaced by this:

`parse_config(path="my_file.yml", loader=yaml.UnsafeLoader)`

**Comment by mkaranasou** [comment]
Hi @maruiz93, thank you for the detailed feature request. Let me know if v1.1.3 works for you 😄
