### ISSUE TITLE
Bump PyYAML dependency to major version 6

### ISSUE THREAD

**Issue by oktavlachs** [mkaranasou/pyaml_env#21]
Hi @mkaranasou ,

thanks for your great project which I am using nearly daily 🙂

Lately I was running into an issue with the latest pyyaml major version 6, as pyaml-env won't let me update because it depends on 5.*

I was wondering, is there anything stopping you from updating to the latest version?

Cheers!

**Comment by mkaranasou** [comment]
Hi @oktavlachs,
Very happy to know this little piece of software is helpful to you :)
There shouldn't be any major problems in upgrading to PyYAML 6, I will test and upgrade it asap.

Cheers!

**Comment by oktavlachs** [comment]
Thanks a lot!

**Comment by mkaranasou** [comment]
Done, let me know if this works for you 🙂

**Comment by oktavlachs** [comment]
Works, thanks! :)

**Comment by oktavlachs** [comment]
Works, thanks! :)
