### ISSUE TITLE
[BUG] add_implicit_resolver() - use of "first" argument required?!

### ISSUE THREAD

**Issue by frank-straetz** [mkaranasou/pyaml_env#25]
**Describe the bug**
`parse_config()` uses this code to decide which YAML entries to actually look at: `loader.add_implicit_resolver(tag, pattern, None)` The third parameter, `first`, is intentionally set to `None`. However, if one takes a look at the [YAML documentation](https://pyyaml.docsforge.com/master/api/yaml/add_implicit_resolver/), this exact argument controls whether a YAML entry should be looked at. 

And indeed, it does not matter which value is passed as `tag`, as it will only be used to tag the entries and process them. But all entries will be processed, prefixed with the `tag` or not. As soon as `first` is also set to the value of `tag`, things start to work as expected: `loader.add_implicit_resolver(tag, pattern, tag)`

**To Reproduce**
1. Add a prefixed and a non-prefixed environment variable substitution attempt to a YAML file, e. g.:
```yaml
test:
  with-prefix: !ENV ${DPT_EXISTING_ENV}
  without-prefix: ${DPT_EXISTING_ENV}
```
2. Try to use `parse_config()` on this YAML file, with `tag` set to different values as well as `None`.
3. Each time both entries will be acted upon, as there is no `first` set and the `pattern` matches.

**Expected behavior**
Only the entries prefixed with the `tag` should be acted upon.

**Additional context**
- Python version: 3.6 (sadly)
- OS: Debian Buster
- pyaml_env: 1.1.5

**Comment by mkaranasou** [comment]
[PR](https://github.com/mkaranasou/pyaml_env/pull/29) ready.
