### ISSUE TITLE
Using defaults for unresolved environment variables result in not resolving the whole value

### ISSUE THREAD

**Issue by rkrell** [mkaranasou/pyaml_env#3]
Another point here in 1.0.1:

Given the following YAML:
```yaml
xxx: !ENV ${DATABASE_HOST:def}
```
The resulting dictionary from _parse_config_ is always
```python
{'xxx': '${DATABASE_HOST:def}'}
```
regardless whether the environment variable `$DATABASE_HOST` is set or not.
This is caused by the default value.

If changing the YAML to:
```yaml
xxx: !ENV ${DATABASE_HOST}
```
and setting `$DATABASE_HOST` to `abc` resolving works:
```python
{'xxx': 'abc'}
```

**Comment by rkrell** [comment]
Couldn't this be caused by not escaping braceleft and braceright in the regular expression for the implicit resolver?
```python
    pattern = re.compile(f'.*?\${{(\w+){default_sep_pattern}}}.*?')
```
->
```python
    pattern = re.compile(f'.*?\$\{{(\w+){default_sep_pattern}}\}.*?')
```

**Comment by rkrell** [comment]
I found the actual reason: I had to add the optional 
```python
config_iterable = parse_config('config.yml', default_sep=':')
```
I did not notice that this is mentioned in the documentation.

In this case - sorry, my fault.

**Comment by mkaranasou** [comment]
Ah, I thought this might get a bit lost in the documentation, will make it more clear, thanks! 👍

**Comment by rkrell** [comment]
> Ah, I thought this might get a bit lost in the documentation, will make it more clear, thanks!

You mentioned it there, but it is not obvious for fast readers like me :-)

From my point of view I would make it a default, ':' or '|', instead of None, and document it in that way.

The only disadvantage would be that you have to handle escapes ot that character, if you want to use it in these expressions for a different purpose than as a separator character. This is also the case for the curly braces '{', '}', which might also get an escape handling, to be able to use all characters in default expressions.
