### ISSUE TITLE
[BUG] Versions conflict due to wrong version constraint in requirements.txt

### ISSUE THREAD

**Issue by nelsyeung** [mkaranasou/pyaml_env#30]
**Describe the bug**
Version conflict due to wrong version constraint in requirements.txt.
Looking at [PEP440](https://peps.python.org/pep-0440/#compatible-release), `>=5.*, <=6.*` doesn't look right. It should be `>=5.0, <7.0`.

**To Reproduce**
1. Create your own package `your-package` that depends on PyYAML 6.0 and pyaml-env 1.2.0
2. Upload the package (I'm using an internal PyPI server)
3. `pip download your-package`
4. Error:

    ```shell
    ERROR: Cannot install your-package and your-package==1.0.0 because these package versions have conflicting dependencies.

    The conflict is caused by:
        your-package 1.0.0 depends on PyYAML<7.0 and >=6.0
        your-package pyaml-env 1.2.0 depends on PyYAML<=6.* and >=5.*
        your-package 2.0.0.dev540 depends on PyYAML<7.0 and >=6.0
        pyaml-env 1.1.5 depends on PyYAML<=6.* and >=5.*
    ```

**Expected behavior**
It shouldn't happen

**Additional context**
- Python version: 3.7+
- OS: macOS 12.6.1

**Comment by mkaranasou** [comment]
👋 thanks, I just released a fix, let me know if it is ok for you.

**Comment by gregdan3** [comment]
Can confirm this works as intended. Thanks for the fix!
