### ISSUE TITLE
[FEATURE] typing final value from lookup or default

### ISSUE THREAD

**Issue by tim-oe** [mkaranasou/pyaml_env#36]
**Is your feature request related to a problem? Please describe.**
in trying to use an integer value the env call makes it into a string 'n'
not sure if this is RTFM on my part, i tried prefixing with !!INT !ENV ${WW_SENSOR_READ_TIMEOUT:90}
but gives me parse errors

**Describe the solution you'd like**
i'd like to get the value into the data type i would be expecting

**Describe alternatives you've considered**
i'm able to wrap getting the value and add conversion.

**Additional context**
sorry again if this is just due to my ignorance with python and the yaml format

**Comment by mkaranasou** [comment]
Hi @tim-oe 👋 

So from [README](https://github.com/mkaranasou/pyaml_env?tab=readme-ov-file#datatype-parsing-with-yamls-tagyamlorg2002), you can do:

```yaml
...
!TAG tag:yaml.org,2002:float ${ENV_TAG2:27017}
...
```

which, in your case would be:
```yaml
!ENV tag:yaml.org,2002:int ${WW_SENSOR_READ_TIMEOUT:90}
```

Can you try and let me know if this works for you?

**Comment by tim-oe** [comment]
that worked.
thank you!
