### ISSUE TITLE
Default values with dots break regular expression

### ISSUE THREAD

**Issue by rkrell** [mkaranasou/pyaml_env#4]
Default values with dots don't resolve due to a wrong regular expression:
```yaml
bind: !ENV ${BIND_HOST:0.0.0.0}:${BIND_PORT:8000}
```

**Comment by rkrell** [comment]
Pull request #5 solved this issue for me, please check whether this fits your needs.

**Comment by mkaranasou** [comment]
Awesome, thanks! I added a few tests for such cases and created v1.0.2
